pipeline {
    agent any

    parameters {
        string(name: 'ENV', defaultValue: 'Prod1', description: 'Env')
        choice(name: 'PERCENTAGE', choices: ['10', '50', '100'], description: 'Percentage to Prod1')
    }

    stages {
        stage("AWS Creds") {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS']]) {
                    echo "Good to go"
                }
            }
        }
        stage("Move traffic") {
            steps {
                script {
                    if (params.PERCENTAGE == '10') {
                        aws elbv2 modify-listener \
                        --listener-arn "arn:aws:elasticloadbalancing:us-east-1:573055573761:listener/app/ecs-alb/92541b0d2f24df2b/c896ffa6e6b1399c" \
                        --default-actions \\
                        '[
                            {
                                "Type": "forward",
                                "Order": 1,
                                "ForwardConfig": {
                                    "TargetGroups": [
                                        {
                                            "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/blue-ecs/7e60168b6484dbaf",
                                            "Weight": 10
                                        },
                                        {
                                            "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/green-ecs/f0fd626ae39f7572",
                                            "Weight": 90
                                        }
                                    ]
                                }
                            }
                        ]'
                    } else if (params.PERCENTAGE == '50') {
                        aws elbv2 modify-listener \
                        --listener-arn "arn:aws:elasticloadbalancing:us-east-1:573055573761:listener/app/ecs-alb/92541b0d2f24df2b/c896ffa6e6b1399c" \
                        --default-actions \
                        '[
                            {
                                \\"Type\\": "forward",
                                \\"Order\\": 1,
                                \\"ForwardConfig\\": {
                                    \\"TargetGroups\\": [
                                        {
                                            \\"TargetGroupArn\\": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/blue-ecs/7e60168b6484dbaf",
                                            \\"Weight\\": 50
                                        },
                                        {
                                            \\"TargetGroupArn\\": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/green-ecs/f0fd626ae39f7572",
                                            \\"Weight\\": 50
                                        }
                                    ]
                                }
                            }
                        ]'
                    } else if (params.PERCENTAGE == "100") {
                        aws elbv2 modify-listener \
                        --listener-arn "arn:aws:elasticloadbalancing:us-east-1:573055573761:listener/app/ecs-alb/92541b0d2f24df2b/c896ffa6e6b1399c" \
                        --default-actions \\
                        '[
                            {
                                "Type": "forward",
                                "Order": 1,
                                "ForwardConfig": {
                                    "TargetGroups": [
                                        {
                                            "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/blue-ecs/7e60168b6484dbaf",
                                            "Weight": 100
                                        },
                                        {
                                            "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:573055573761:targetgroup/green-ecs/f0fd626ae39f7572",
                                            "Weight": 0
                                        }
                                    ]
                                }
                            }
                        ]'
                    } else {
                        echo "Wrong value given"
                    }
                }
            }
        }
    }
}
